# /// script
# requires-python = ">=3.12,<3.13"
# dependencies = [
#     "marimo>=0.23,<1",
#     "pandas",
#     "matplotlib",
# ]
# ///

# ruff: noqa: I002

import marimo

__generated_with = "0.23.13"
app = marimo.App(width="medium")


@app.cell(hide_code=True)
def _():
    import marimo as mo

    return (mo,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Title

    `<Short descriptive QC title>`

    **One-line verdict.**
    `<Pass / rerun / reject verdict and the single reason for it.>`
    """)
    return


@app.cell
def _():
    import platform
    import subprocess
    import sys
    from datetime import datetime
    from pathlib import Path

    import marimo as marimo_pkg
    import matplotlib.pyplot as plt
    import pandas as pd

    from myproject.figures.plot_style import use_plot_style
    from myproject.paths import repo_root

    use_plot_style()

    return (
        Path,
        datetime,
        marimo_pkg,
        pd,
        platform,
        plt,
        repo_root,
        subprocess,
        sys,
    )


@app.cell
def _(Path, repo_root):
    # Replace placeholders before using this template for a real QC report.
    ROOT = repo_root(Path(__file__))
    REPORT_ID = "replace_with_analysis_id"
    ANALYST = "<your name>"

    INPUT_FILES = {
        "primary_table": ROOT / "data/processed/<stage>/<file>.tsv",
        "input_manifest": ROOT / "data/meta/<inputs>.toml",
        "reference": ROOT / "data/external/<reference>",
    }
    OUTPUT_FILES = {
        "figures": ROOT / "results" / REPORT_ID,
        "tables": ROOT / "data/processed" / REPORT_ID,
        "html_report": ROOT / "reports" / f"{REPORT_ID}.html",
    }
    ANALYSIS_PARAMETERS = {
        "dataset": "<subset, period, or condition checked>",
        "normalization": "<normalization or scaling method>",
        "pass_fail_threshold": "<metric and cutoff that defines pass/fail>",
    }
    return ANALYSIS_PARAMETERS, ANALYST, INPUT_FILES, OUTPUT_FILES, ROOT


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Purpose

    State what is being checked and the rule that decides pass/fail.

    - Check target: `<Which stage output, records, or subsets?>`
    - Pass criterion: `<Metric and cutoff, fixed before inspecting the data.>`
    - Decision supported: `<Pass downstream, rerun with changes, or reject.>`
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Background

    Give only the context needed to judge the output.

    - Pipeline context: `<upstream stage that produced the input, downstream use>`
    - Known failure modes: `<what tends to go wrong at this stage>`
    - Key assumption: `<assumption that affects the verdict>`
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Input data

    | Input | Source | Role |
    | --- | --- | --- |
    | `<primary_table>` | `<processed TSV>` | `<main measurements>` |
    | `<input_manifest>` | `<TOML manifest>` | `<list of source files>` |
    | `<reference>` | `<lookup table, mapping, or code list>` | `<labels and keys>` |

    Record whether inputs are generated by this notebook or by an upstream
    CLI command (the exact command goes in the reproducibility notes).
    """)
    return


@app.cell(hide_code=True)
def _(ANALYSIS_PARAMETERS, mo):
    parameter_rows = "\n".join(
        f"| `{key}` | `{value}` |" for key, value in ANALYSIS_PARAMETERS.items()
    )
    mo.md(f"""
    ## Methods

    Summarize the QC procedure in the order it runs. Keep implementation
    details in code cells.

    1. `<Load and validate inputs.>`
    2. `<Compute the QC metric(s).>`
    3. `<Compare each metric against its fixed threshold.>`
    4. `<Emit the verdict, figures, and machine-readable outputs.>`

    Fix the threshold before inspecting the data, and do not move it to fit
    the result.

    Analysis parameters:

    | Parameter | Value |
    | --- | --- |
    {parameter_rows}
    """)
    return


@app.cell
def _(INPUT_FILES, mo, pd):
    # Example load cell (house style). Replace with the real QC inputs.
    _primary_table = INPUT_FILES["primary_table"]
    if _primary_table.exists():
        primary_df = pd.read_csv(_primary_table, sep="\t")
        if primary_df.empty:
            raise ValueError(f"{_primary_table} is empty")
        primary_shape = primary_df.shape
        _load_msg = (
            f"Loaded `{_primary_table.name}` — {primary_shape[0]} rows "
            f"x {primary_shape[1]} cols."
        )
    else:
        primary_df = None
        primary_shape = None
        _load_msg = (
            "⚠️ example cell — point `INPUT_FILES['primary_table']` at a real "
            "TSV to activate the load / figure / table skeleton below."
        )
    mo.md(_load_msg)
    return primary_df, primary_shape


@app.cell
def _(OUTPUT_FILES, mo, plt, primary_df):
    # Example figure cell. Replace with the real QC plot, then save it under
    # results/<stage>/.
    if primary_df is not None:
        _fig, _ax = plt.subplots(figsize=(6, 4))
        _ax.plot(range(len(primary_df)))
        _ax.set_title("Example figure — replace with the real QC plot")
        plt.tight_layout()
        OUTPUT_FILES["figures"].mkdir(parents=True, exist_ok=True)
        _fig.savefig(OUTPUT_FILES["figures"] / "example_figure.png")
    else:
        _fig = None
    _fig if _fig is not None else mo.md(
        "⚠️ example figure cell — activates once inputs are loaded."
    )
    return


@app.cell
def _(OUTPUT_FILES, mo, primary_df):
    # Example table cell. Replace with the real QC table, then save it under
    # data/processed/<stage>/.
    if primary_df is not None:
        _example_table = primary_df.head(10)
        OUTPUT_FILES["tables"].mkdir(parents=True, exist_ok=True)
        _example_table.to_csv(
            OUTPUT_FILES["tables"] / "example_table.tsv", sep="\t", index=False
        )
        _table_msg = (
            f"Wrote example table ({len(_example_table)} rows) to "
            f"`{OUTPUT_FILES['tables'].name}/example_table.tsv`."
        )
    else:
        _table_msg = "⚠️ example table cell — activates once inputs are loaded."
    mo.md(_table_msg)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Results

    Report the QC observations before the verdict.

    - Metric vs threshold: `<measured value(s) against the fixed cutoff>`
    - Verdict: `<pass / fail, as a deterministic function of the comparison>`
    - Flagged cases: `<a few examples that failed or look suspicious>`

    Add figures and tables immediately after the text that introduces them.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Discussion

    Turn the verdict into an action.

    - Interpretation: `<What does the QC result mean for this stage's output?>`
    - Consistency check: `<Does it agree with upstream QC or prior runs?>`
    - Next action: `<Pass downstream, rerun with changes, or reject output.>`
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Limitations

    List constraints that could change the verdict.

    - Data limitation: `<sample size, coverage, missing periods, noisy subsets>`
    - Method limitation: `<threshold choice, preprocessing step, confounder>`
    - Review status: `<manual QC pending, partial data, draft analysis>`
    """)
    return


@app.cell(hide_code=True)
def _(OUTPUT_FILES, ROOT, mo):
    # Repo-relative: this table is rendered into a tracked HTML, so an absolute
    # path would bake one machine's checkout into the report.
    output_rows = "\n".join(
        f"| `{key}` | `{path.relative_to(ROOT)}` | `<what this artifact contains>` |"
        for key, path in OUTPUT_FILES.items()
    )
    mo.md(f"""
    ## Output files

    | Output | Path | Description |
    | --- | --- | --- |
    {output_rows}

    Keep rendered figures under `results/<stage>/` and machine-readable files under
    `data/processed/<stage>/` unless the stage has a documented exception.
    """)
    return


@app.cell(hide_code=True)
def _(
    ANALYST,
    INPUT_FILES,
    ROOT,
    datetime,
    marimo_pkg,
    mo,
    platform,
    primary_shape,
    subprocess,
    sys,
):
    try:
        _sha = subprocess.run(
            ["git", "-C", str(ROOT), "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except (subprocess.SubprocessError, OSError):
        _sha = "unknown"

    _now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    _input_lines = []
    for _name, _path in INPUT_FILES.items():
        if _path.exists():
            _mtime = datetime.fromtimestamp(_path.stat().st_mtime).strftime(
                "%Y-%m-%d %H:%M"
            )
            _rows = (
                f", {primary_shape[0]} rows"
                if _name == "primary_table" and primary_shape is not None
                else ""
            )
            _input_lines.append(f"    - Input `{_name}`: modified {_mtime}{_rows}")
        else:
            _input_lines.append(f"    - Input `{_name}`: missing (placeholder)")
    _input_block = "\n".join(_input_lines)

    run_command = "uv run marimo run notebooks/<notebook>.py"
    export_command = (
        "uv run marimo export html notebooks/<notebook>.py -o reports/<notebook>.html"
    )
    mo.md(f"""
    ## Reproducibility notes

    - Analyst: `{ANALYST}`
    - Run timestamp: `{_now}`
    - Code version (git): `{_sha}`
    {_input_block}
    - For each input, also record the generating CLI command or run-id.
    - Dependencies: pinned by `uv.lock` at the repo root.
    - Run command: `{run_command}`
    - Export command: `{export_command}`
    - Python: `{sys.version.split()[0]}`
    - Platform: `{platform.platform()}`
    - marimo: `{marimo_pkg.__version__}`
    - Random seed: `<seed or not applicable>`
    - External tools: `<CLI commands, reference data, or database versions>`
    """)
    return


if __name__ == "__main__":
    app.run()
